### ISSUE TITLE
USER STORY: Optimal Running Time

### ISSUE THREAD

**Issue by Barry1701** [Barry1701/My-First-Agile-Project#3]
In order to **contribute to selection of the best time for running** as an **amateur fitness enthusiast** I can **participate in weekly "Optimal Running Time" poll .**

 ### Acceptance Criteria:

- Acceptance Criteria 1:  The user can choose one of the options related to the best running time.
- Acceptance Criteria 2:  An anonymous user can participate in the poll.
- Acceptance Criteria 3: The user can view the current poll results.

### Tasks:

- [ ] Design and integrate a poll on the Love Running home page where users can vote for their favorite running tracks.
- [ ] Develop a feature that allows anonymous users to participate in the poll.
- [ ] Implement a mechanism to ensure the anonymity of users who choose not to log in but still want to vote for their favorite running spots.
- [ ] Create a user interface component to display the current poll results.
