### ISSUE TITLE
USER STORY: Manage User Comments

### ISSUE THREAD

**Issue by Barry1701** [Barry1701/My-First-Agile-Project#6]
As a **site administrator** I can **manage user comments** so that **I can maintain positive and engaging community**.

### Acceptance Criteria:
- Acceptance Criteria 1: The administrator can delete inappropriate comments.
- Acceptance Criteria 2: The administrator can reply to user comments.
- Acceptance Criteria 3:  Deleted comments are no longer visible to users.

### Tasks:
- [ ] Implement a comment moderation interface for administrators.
- [ ] Implement the ability for administrators to reply to user comments.
- [ ] Develop functionality to delete comments.
